export interface Carreira {
    id: number;
    titulo: string;
    imgSrc: string;
    tipo: string;
    estrelas: number;
    breveDescricao: string;
    salario: string;
    cargaHoraria: string;
    observacao: string;
    inteligencias: string;
}

export const carreiraData: Carreira[] = [
    {
        id: 1,
        titulo: "Medicina",
        imgSrc: "/img/naturalista.svg",
        tipo: "interpessoal 40%; Naturalista 40%; Lógico-matemática 20%",
        estrelas: 3,
        breveDescricao:
            "A Medicina é a ciência responsável por prevenir, diagnosticar e tratar doenças, promovendo a saúde e o bem-estar das pessoas...",
        salario: "R$ 17.742,78",
        cargaHoraria: "20 horas semanais",
        observacao: "Longo período de estudo.",
        inteligencias: "Interpessoal 40%; Naturalista 40%; Lógico-matemática 20%",
    },
    {
        id: 2,
        titulo: "Direito",
        imgSrc: "/img/linguistica.svg",
        tipo: "Linguística 60%; Interpessoal 20%; Lógico-matemática 20%",
        estrelas: 3,
        breveDescricao:
            "Atua na defesa dos direitos ou interesses de indivíduos, empresas e instituições em qualquer instância, avalia os casos, provas orais e documentais, recomenda procedimentos e encaminha processos para justiça. Realiza pesquisas jurídicas, elabora peças iniciais, contestações, petições e recursos, acompanha e comparece em audiências.",
        salario: "R$ 4.578,45",
        cargaHoraria: "20 horas semanais",
        observacao: "Longo estudo e necessidade de ser um bom argumentador.",
        inteligencias: "Linguística 60%; Interpessoal 20%; Lógico-matemática 20%",
    },
    {
        id: 3,
        titulo: "Psicologia",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 40%; Existencial 35%; Intrapessoal 25%",
        estrelas: 3,
        breveDescricao:
            "A Psicologia é o estudo da mente e do comportamento humano, bem como suas interações com o meio ambiente. É uma ciência que visa diagnosticar, compreender, explicar e promover mudanças nos comportamentos humanos.",
        salario: "R$ 2.660,00",
        cargaHoraria: "30 horas semanais",
        observacao: "",
        inteligencias: "Interpessoal 40%; Existencial 35%; Intrapessoal 25%",
    },
    {
        id: 4,
        titulo: "Pedagogia",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 60%; Linguística 30%; Existencial 10%",
        estrelas: 3,
        breveDescricao:
            "A Pedagogia é a ciência que estuda a educação, seus processos, métodos e técnicas para a formação de indivíduos. Estuda a relação entre professor e aluno, bem como a interação entre os membros da comunidade educacional, além da conexão entre ensino e aprendizagem.",
        salario: "R$ 2.595,03 até R$ 5.754,30",
        cargaHoraria: "40 horas semanais",
        observacao: "",
        inteligencias: "Interpessoal 60%; Linguística 30%; Existencial 10%",
    },
    {
        id: 5,
        titulo: "Finanças",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática 85%; Interpessoal 15%",
        estrelas: 3,
        breveDescricao:
            "Gerir adequadamente as finanças, seja no âmbito particular ou público, integra o processo determinante para o sucesso orçamentário de organizações e empresas. Os procedimentos englobam a destinação de recursos para setores específicos, controle de gastos, geração de receitas, investimentos, entre outros fatores que contribuem para o aprimoramento do fluxo de caixa.",
        salario: "R$ 4.778 até R$ 26.750",
        cargaHoraria: "30 horas semanais",
        observacao: "",
        inteligencias: "Lógico-matemática 85%; Interpessoal 15%",
    },
    {
        id: 6,
        titulo: "Marketing",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 40%; Linguística 30%; Espacial 30%",
        estrelas: 3,
        breveDescricao:
            "Marketing é o conjunto de estratégias e ações que visam criar valor para o cliente e gerar lucro para a empresa. Envolve atividades como pesquisa de mercado, desenvolvimento de produtos, comunicação, promoção e distribuição, com o objetivo de identificar, satisfazer e fidelizar, garantindo a competitividade e o sucesso da empresa no mercado.",
        salario: "R$ 2.326 e R$ 22.200",
        cargaHoraria: "42 horas semanais",
        observacao: "",
        inteligencias: "Interpessoal 40%; Linguística 30%; Espacial 30%",
    },
    {
        id: 7,
        titulo: "Nutrição",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 40%; Interpessoal 35%; Corporal-cinestésico 25%",
        estrelas: 3,
        breveDescricao:
            "A nutrição é a ciência que estuda os nutrientes presentes nos alimentos, suas funções no organismo e a forma como devem ser consumidos para garantir uma alimentação equilibrada e saudável, visando a prevenção e tratamento de doenças e a promoção da saúde.",
        salario: "média de R$ 2.917,29",
        cargaHoraria: "44 horas semanais",
        observacao: "",
        inteligencias: "Naturalista 40%; Interpessoal 35%; Corporal-cinestésico 25%",
    },
    {
        id: 8,
        titulo: "Odontologia",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 40%; Interpessoal 35%; Corporal-cinestésico 25%",
        estrelas: 3,
        breveDescricao:
            "A Odontologia é a ciência que estuda e trata as doenças relacionadas à saúde bucal. O objetivo dessa área é prevenir e solucionar problemas bucais, além de promover a estética e a função dos dentes e tecidos orais. Os profissionais graduados em Odontologia são chamados de odontologistas ou dentistas.",
        salario: "média de R$ 4.122,98",
        cargaHoraria: "30 horas semanais",
        observacao: "Não ter problemas com questões de higiene bucal alheia.",
        inteligencias: "Naturalista 40%; Interpessoal 35%; Corporal-cinestésico 25%",
    },
    {
        id: 9,
        titulo: "Ciência da Computação",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática 70%; Espacial 30%",
        estrelas: 3,
        breveDescricao:
            "A Ciência da Computação é o campo que estuda o desenvolvimento de algoritmos, estruturas de dados e sistemas de computação, abrangendo áreas como programação, inteligência artificial, redes de computadores e segurança. Seu objetivo é resolver problemas e criar tecnologias relacionadas à computação.",
        salario: "R$ 3.368,11",
        cargaHoraria: "20 horas semanais",
        observacao: "",
        inteligencias: "Lógico-matemática 70%; Espacial 30%",
    },
    {
        id: 10,
        titulo: "Turismo",
        imgSrc: "/img/espacial.svg",
        tipo: "Espacial 30%; Naturalista 30%; Linguística 20%; Interpessoal 20%",
        estrelas: 3,
        breveDescricao:
            "Turismo é a atividade que envolve o deslocamento temporário de pessoas para fora do seu ambiente habitual, com fins de lazer, negócios ou outros motivos. Envolve diversos serviços, como hospedagem, transporte, alimentação e atrações turísticas, gerando impactos econômicos, sociais e culturais.",
        salario: "R$ 8.564,13",
        cargaHoraria: "40 horas semanais",
        observacao: "",
        inteligencias: "Espacial 30%; Naturalista 30%; Linguística 20%; Interpessoal 20%",
    },
    {
        id: 11,
        titulo: "Cinema",
        imgSrc: "/img/existencial.svg",
        tipo: "Existencial 35%; Interpessoal 30%; Intrapessoal 25%; Musical 10%",
        estrelas: 3,
        breveDescricao:
            "A área de cinema engloba o estudo e prática da produção audiovisual, abrangendo desde a criação de roteiros e direção até a fotografia, edição e design de som. É um campo criativo e multidisciplinar, onde a narrativa visual é explorada como forma de expressão artística e comunicação, visando criar experiências cinematográficas impactantes.",
        salario: "R$ 3.800,00 até R$ 6.700,00",
        cargaHoraria: "36 horas semanais",
        observacao: "",
        inteligencias: "Existencial 35%; Interpessoal 30%; Intrapessoal 25%; Musical 10%",
    },
    {
        id: 12,
        titulo: "Letras",
        imgSrc: "/img/linguistica.svg",
        tipo: "Linguística 70%; Intrapessoal 30%",
        estrelas: 3,
        breveDescricao:
            "A área de Letras é um campo do conhecimento que se dedica ao estudo da linguagem e da literatura, abrangendo diversas disciplinas que buscam aprofundar o conhecimento sobre as línguas, a produção literária, a cultura, a história, a filosofia e a comunicação humana em suas diferentes formas e modalidades.",
        salario: "R$ 2.522,00 até R$ 4.327,62",
        cargaHoraria: "44 horas semanais",
        observacao: "",
        inteligencias: "Linguística 70%; Intrapessoal 30%",
    },
    {
        id: 13,
        titulo: "Design Gráfico",
        imgSrc: "/img/espacial.svg",
        tipo: "Espacial 60%; Interpessoal 20%; Musical 20%",
        estrelas: 3,
        breveDescricao:
            "Design gráfico é a área que envolve a criação e desenvolvimento de elementos visuais para diversos meios de comunicação, como impressos, digitais, audiovisuais, entre outros. O profissional de design gráfico utiliza conceitos de arte, tipografia, composição, cores e tecnologias para desenvolver projetos que atendam às necessidades e objetivos de seus clientes ou empresas.",
        salario: "R$ 1.200,00 até R$ 3.100,00",
        cargaHoraria: "43 horas semanais",
        observacao: "",
        inteligencias: "Espacial 60%; Interpessoal 20%; Musical 20%",
    },
    {
        id: 14,
        titulo: "Música",
        imgSrc: "/img/musica.svg",
        tipo: "Musical 60%; Linguística 20%; Interpessoal 20%",
        estrelas: 3,
        breveDescricao:
            "A Música é uma forma de expressão artística. É a área que combina sons e ritmos para a criação de canções e harmonias, seja para transmitir emoções, contar histórias ou apresentar mensagens. Ela pode ser utilizada para comemorar, relaxar, motivar, expressar, mover e conectar pessoas.",
        salario: "R$ 4.446,33",
        cargaHoraria: "",
        observacao: "",
        inteligencias: "Musical 60%; Linguística 20%; Interpessoal 20%",
    },
    {
        id: 15,
        titulo: "Relações Públicas",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 70%; Linguística 30%",
        estrelas: 3,
        breveDescricao:
            "É a prática de criar e manter boas relações entre uma organização e seu público-alvo. As relações públicas envolvem a criação de conteúdo, ações de marketing e comunicação para ajudar a construir uma imagem positiva da marca. Elas também podem ajudar a melhorar a reputação da empresa e aumentar a conscientização do público.",
        salario: "R$ 4.711,01",
        cargaHoraria: "",
        observacao: "",
        inteligencias: "Interpessoal 70%; Linguística 30%",
    },
    {
        id: 16,
        titulo: "Jornalismo",
        imgSrc: "/img/linguistica.svg",
        tipo: "Linguística 50%; Interpessoal 50%",
        estrelas: 3,
        breveDescricao:
            "É a prática de investigar, coletar, editar e publicar notícias e informações para o público. O jornalismo envolve a coleta de fatos, entrevistas, pesquisas, análises e escrita para informar o público sobre eventos atuais e relevantes.",
        salario: "R$ 3.361,54",
        cargaHoraria: "",
        observacao: "",
        inteligencias: "Linguística 50%; Interpessoal 50%",
    },
    {
        id: 17,
        titulo: "Arquitetura e Urbanismo",
        imgSrc: "/img/espacial.svg",
        tipo: "Espacial 70%; Lógico-matemática 30%",
        estrelas: 3,
        breveDescricao:
            "A área de Arquitetura e Urbanismo capacita o profissional não apenas para projetar, desenhar e criar espaços e construções, mas também para atuar na preservação, conservação, restauração, reconstrução e reutilização de edificações, tanto residenciais quanto empresariais.",
        salario: "R$ 2.994,93",
        cargaHoraria: "",
        observacao: "",
        inteligencias: "Espacial 70%; Lógico-matemática 30%",
    },
    {
        id: 18,
        titulo: "Agronomia",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 50%; Espacial 30%; Corporal cinestésica 20%",
        estrelas: 3,
        breveDescricao:
            "Agronomia é um campo da Gestão Ambiental e abarcado pelas ciências agrárias, sendo uma área multidisciplinar que inclui subáreas aplicadas das ciências naturais, exatas, sociais e econômicas.",
        salario: "R$ 6.816 em média",
        cargaHoraria: "8 horas por dia",
        observacao: "Se interessar por plantações.",
        inteligencias: "Naturalista 50%; Espacial 30%; Corporal cinestésica 20%",
    },
    {
        id: 19,
        titulo: "Biotecnologia",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 70%; Lógico-matemática 30%",
        estrelas: 3,
        breveDescricao:
            "Biotecnologia é a área de estudo e desenvolvimento de seres modificados em laboratório com o intuito de promover o aprimoramento de técnicas em vários setores da sociedade (indústria, saúde, meio ambiente, etc.).",
        salario: "R$ 4.364,67 em média",
        cargaHoraria: "40 horas semanais",
        observacao: "",
        inteligencias: "Naturalista 70%; Lógico-matemática 30%",
    },
    {
        id: 20,
        titulo: "Ecologia",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista",
        estrelas: 3,
        breveDescricao:
            "Analisa o impacto das ações dos seres vivos no meio ambiente e busca soluções para evitar desequilíbrios ambientais causados por essas ações. Também investiga o funcionamento e a estrutura dos ecossistemas.",
        salario: "R$ 4.596,37 em média",
        cargaHoraria: "42 horas semanais",
        observacao: "",
        inteligencias: "Naturalista",
    },
    {
        id: 21,
        titulo: "Geologia",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 70%; Espacial 30%",
        estrelas: 3,
        breveDescricao:
            "Geologia é a ciência que estuda a origem, a formação, a estrutura e a composição da crosta terrestre e as alterações sofridas no decorrer do tempo. O geólogo estuda a ação das forças naturas sobre o planeta e seus efeitos, como a erosão, a glaciação e a desertificação.",
        salario: "R$ 1.801,23 em média",
        cargaHoraria: "44 horas semanais",
        observacao: "",
        inteligencias: "Naturalista 70%; Espacial 30%",
    },
    {
        id: 22,
        titulo: "Medicina veterinária",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 60%; Interpessoal 40%",
        estrelas: 3,
        breveDescricao:
            "O Médico Veterinário realiza atendimento médico a toda classe de animais, atuando na avaliação, diagnóstico e tratamento rotineiros da área, além da aplicação de vacinas, realização de exames e cirurgias. Esse profissional também pode atuar de forma preventiva, propondo medidas para evitar ou conter o aparecimento de doenças e pragas dos animais.",
        salario: "R$ 4.087,87 em média",
        cargaHoraria: "39 horas semanais",
        observacao: "",
        inteligencias: "Naturalista 60%; Interpessoal 40%",
    },
    {
        id: 23,
        titulo: "Meteorologia",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 60%; Espacial 30%; Linguistica 10%",
        estrelas: 3,
        breveDescricao:
            "O curso de Meteorologia, também chamado de Ciências Atmosféricas, forma profissionais capacitados para interpretar os mais variados fenômenos que ocorrem na atmosfera. O pensamento crítico e o poder de análise são características que se destacam nesta formação.",
        salario: "R$ 3.995,95 em média",
        cargaHoraria: "42 horas semanais",
        observacao: "",
        inteligencias: "Naturalista 60%; Espacial 30%; Linguistica 10%",
    },
    {
        id: 24,
        titulo: "Oceanografia",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 80%; Existencial 20%",
        estrelas: 3,
        breveDescricao:
            "O trabalho de um oceanógrafo envolve coletar amostras dos ambientes aquáticos, determinar as condições físicas, químicas e biológicas destes ambientes, pesquisar sobre as formas de vida ali encontradas e suas características.",
        salario: "R$ 4.987,32 em média",
        cargaHoraria: "40 horas semanais",
        observacao: "",
        inteligencias: "Naturalista 80%; Existencial 20%",
    },
    {
        id: 25,
        titulo: "Bioquímica",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 80%; Lógico-matemática 20%",
        estrelas: 3,
        breveDescricao:
            "O bioquímico pesquisa e aplica processos biológicos (como fermentação e reações naturais entre elementos) na transformação de alimentos, produção de remédios e combustíveis. Desempenha um papel fundamental tanto em institutos de pesquisa quanto na indústria médica, farmacêutica, alimentícia, cosmética ou agrícola.",
        salario: "R$ 3.987,54 em média",
        cargaHoraria: "39 horas semanais",
        observacao: "",
        inteligencias: "Naturalista 80%; Lógico-matemática 20%",
    },
    {
        id: 26,
        titulo: "Biofísica",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 40%; Lógico-matemática 30%; Existencial 20%; Espacial 10%",
        estrelas: 3,
        breveDescricao:
            "O biofísico possui conhecimentos físicos e os aplica em pesquisas biológicas. A área de conhecimento de um biofísico abrange a análise de fenômenos da vida, desde a escala molecular até cenários mais amplos como os ecossistemas. Desta forma, a compreensão do profissional ocorre mediante o entendimento da física do cotidiano com aplicação ao estudo da natureza e biologia.",
        salario: "R$ 3.000,00 em média",
        cargaHoraria: "40 horas semanais",
        observacao: "",
        inteligencias: "Naturalista 40%; Lógico-matemática 30%; Existencial 20%; Espacial 10%",
    },
    {
        id: 27,
        titulo: "Biomedicina",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 40%; Lógico-matemática 35%; Interpessoal 25%",
        estrelas: 3,
        breveDescricao:
            "A Biomedicina é uma área científica que une a Biologia e a Medicina para estudar doenças humanas, seus elementos ambientais e epidemiológicos. Ela busca entender como as doenças se desenvolvem e como podem ser tratadas. A área abrange o desenvolvimento de novas tecnologias e medicamentos.",
        salario: "R$ 2.376,01 em média",
        cargaHoraria: "44 horas semanais",
        observacao: "",
        inteligencias: "Naturalista 40%; Lógico-matemática 35%; Interpessoal 25%",
    },
    {
        id: 28,
        titulo: "Ciências Biológicas",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 50%; Lógico-matemática 30%; Existencial 20%",
        estrelas: 3,
        breveDescricao:
            "Ciências Biológicas é um campo do conhecimento que estuda a vida — o ser humano, fauna, flora e outros seres vivos — e a forma como ela interage com o meio ambiente. É uma área voltada para a pesquisa sobre a origem, evolução, adaptação e o funcionamento dos organismos e para a conservação dos recursos naturais.",
        salario: "R$ 3.366,67 em média",
        cargaHoraria: "40 horas semanais",
        observacao: "",
        inteligencias: "Naturalista 50%; Lógico-matemática 30%; Existencial 20%",
    },
    {
        id: 29,
        titulo: "Educação Física",
        imgSrc: "/img/corporalCin.webp",
        tipo: "Corporal-cinestésica 80%; Naturalista 10%; Interpessoal 10%",
        estrelas: 3,
        breveDescricao:
            "Educação Física é uma área do conhecimento humano ligada às práticas corporais historicamente produzidas pela humanidade e visa à formação do homem capaz de conduzir-se plenamente em suas atividades.",
        salario: "R$ 2.400 em média",
        cargaHoraria: "8 horas por dia",
        observacao: "",
        inteligencias: "Corporal-cinestésica 80%; Naturalista 10%; Interpessoal 10%",
    },
    {
        id: 30,
        titulo: "Enfermagem",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 60%; Naturalista 30%; Linguística 10%",
        estrelas: 3,
        breveDescricao:
            "A enfermagem é uma ciência cujo objetivo é a implantação do tratamento de doenças e o cuidado ao ser humano, individualmente, na família ou em comunidade de modo integral e holístico.",
        salario: "R$ 3.136 em média",
        cargaHoraria: "44 horas semanais",
        observacao: "",
        inteligencias: "Interpessoal 60%; Naturalista 30%; Linguística 10%",
    },
    {
        id: 31,
        titulo: "Estética",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 50%; Naturalista 30%; Espacial 20%",
        estrelas: 3,
        breveDescricao:
            "O curso de Estética e Cosmética forma profissionais responsáveis por gerar bem-estar e conservar a beleza e a saúde dos pacientes. Mais do que melhorar a aparência, esse profissional ajuda a trazer mais autoestima às pessoas.",
        salario: "R$ 1.880,63 em média",
        cargaHoraria: "43 horas semanais",
        observacao: "",
        inteligencias: "Interpessoal 50%; Naturalista 30%; Espacial 20%",
    },
    {
        id: 32,
        titulo: "Farmácia",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 60%; Lógico-matemática 20%; Interpessoal 20%",
        estrelas: 3,
        breveDescricao:
            "A Farmácia é a ciência responsável por desenvolver, fabricar, armazenar, distribuir e promover medicamentos e outros produtos farmacêuticos. Os profissionais da área também orientam os pacientes sobre os medicamentos prescritos, analisam a segurança e eficácia dos fármacos, e supervisionam os processos de produção.",
        salario: "R$ 3.916,48 em média",
        cargaHoraria: "40 horas semanais",
        observacao: "",
        inteligencias: "Naturalista 60%; Lógico-matemática 20%; Interpessoal 20%",
    },
    {
        id: 33,
        titulo: "Fisioterapia",
        imgSrc: "/img/corporalCin.webp",
        tipo: "Corporal-cinestésica 60%; Interpessoal 28%; Naturalista 12%",
        estrelas: 3,
        breveDescricao:
            "O fisioterapeuta é o profissional responsável por prevenir, diagnosticar e tratar problemas relacionados às funções e aos movimentos do corpo.",
        salario: "Em média R$ 2.773,00",
        cargaHoraria: "30 horas semanais",
        observacao: "",
        inteligencias: "Corporal-cinestésica 60%; Interpessoal 28%; Naturalista 12%",
    },
    {
        id: 34,
        titulo: "Fonoaudiologia",
        imgSrc: "/img/linguistica.svg",
        tipo: "Linguística 50%; Musical 20%; Interpessoal 15%; Corporal-cinestésica 15%",
        estrelas: 3,
        breveDescricao:
            "É a especialidade que trabalha com os aspectos que envolvem a comunicação oral e escrita.",
        salario: "Em média R$ 3.158,00",
        cargaHoraria: "30 horas semanais",
        observacao: "",
        inteligencias: "Linguística 50%; Musical 20%; Interpessoal 15%; Corporal-cinestésica 15%",
    },
    {
        id: 35,
        titulo: "Astronomia",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 50%; Existencial 40%; Espacial 10%",
        estrelas: 3,
        breveDescricao:
            "Astronomia é uma ciência natural que estuda corpos celestes e fenômenos que se originam fora da atmosfera da Terra.",
        salario: "R$ 2.500 em média",
        cargaHoraria: "8h a 9h por dia",
        observacao: "Os melhores salários são em Piauí, Tocantins e Distrito Federal.",
        inteligencias: "Naturalista 50%; Existencial 40%; Espacial 10%",
    },
    {
        id: 36,
        titulo: "Musicoterapia",
        imgSrc: "/img/musica.svg",
        tipo: "Musical 40%; Interpessoal 30%; Linguística 20%; Intrapessoal 10%",
        estrelas: 3,
        breveDescricao:
            "Musicoterapia é uma prática com música no contexto clínico de tratamento, reabilitação ou prevenção de saúde e bem-estar.",
        salario: "R$ 2.957 em média",
        cargaHoraria: "40h semanais",
        observacao: "",
        inteligencias: "Musical 40%; Interpessoal 30%; Linguística 20%; Intrapessoal 10%",
    },
    {
        id: 37,
        titulo: "Quiropraxia",
        imgSrc: "/img/corporalCin.webp",
        tipo: "Corporal-cinestésica 50%; Interpessoal 30%; Naturalista 20%",
        estrelas: 3,
        breveDescricao:
            "A quiropraxia é uma profissão na área de saúde que se dedica ao diagnóstico, tratamento e prevenção de problemas do sistema neuro-músculo-esquelético, ou seja, que envolvem as articulações, músculos, tendões, ossos, nervos e outras estruturas responsáveis pelo movimento do corpo.",
        salario: "R$ 3.838 em média",
        cargaHoraria: "44h por semana",
        observacao: "Não ter gatilhos com estalos.",
        inteligencias: "Corporal-cinestésica 50%; Interpessoal 30%; Naturalista 20%",
    },
    {
        id: 38,
        titulo: "Engenharia Aeronáutica",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática 40%; Espacial 40%; Naturalista 20%",
        estrelas: 3,
        breveDescricao:
            "No processo de desenvolvimento de uma aeronave, o engenheiro aeronáutico trabalha em conjunto com outros profissionais, como mecânicos, projetistas, cientistas e pilotos. Eles são responsáveis por avaliar as necessidades e demandas dos clientes e traduzi-las em especificações técnicas para a construção de aeronaves.",
        salario: "R$ 14.868 por mês",
        cargaHoraria: "42 horas semanais",
        observacao: "Ser bom em planejamento.",
        inteligencias: "Lógico-matemática 40%; Espacial 40%; Naturalista 20%",
    },
    {
        id: 39,
        titulo: "Engenharia Social",
        imgSrc: "/img/intrapessoal.svg",
        tipo: "intrapessoal",
        estrelas: 3,
        breveDescricao:
            "A Engenharia Social é uma prática que se utiliza de técnicas psicológicas e manipulação para obter informações confidenciais, acesso a sistemas de computadores e realizar ações não autorizadas.",
        salario: "Varia amplamente de acordo com a aplicação.",
        cargaHoraria: "Depende da aplicação e do contexto.",
        observacao:
            "A Engenharia Social é uma área ética sensível, muitas vezes associada a atividades ilícitas. Esteja ciente das implicações legais e éticas ao considerar essa carreira.",
        inteligencias: "intrapessoal",
    },
    {
        id: 40,
        titulo: "Engenharia Civil",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática 50%; Espacial 50%",
        estrelas: 4,
        breveDescricao:
            "A Engenharia Civil aplica conhecimentos matemáticos, científicos e tecnológicos para projetar, construir e manter infraestruturas como edifícios, pontes, estradas, túneis, sistemas de água e esgoto, entre outros.",
        salario: "Em média R$ 6.815,10",
        cargaHoraria: "44h semanais",
        observacao: "Ser bom em planejamento.",
        inteligencias: "Lógico-matemática 50%; Espacial 50%",
    },
    {
        id: 41,
        titulo: "Engenharia Elétrica",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática 60%; Naturalista 30%; Espacial 10%",
        estrelas: 4,
        breveDescricao:
            "Engenharia Elétrica é o ramo da engenharia que trabalha com os estudos e aplicações da eletricidade, eletromagnetismo e eletrônica.",
        salario: "R$ 7.500 em média",
        cargaHoraria: "41 horas semanais",
        observacao: "Gostar de física.",
        inteligencias: "Lógico-matemática 60%; Naturalista 30%; Espacial 10%",
    },
    {
        id: 42,
        titulo: "Engenharia Mecânica",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática 40%; Espacial 40%; Corporal cinestésica 20%",
        estrelas: 4,
        breveDescricao:
            "Engenheiros mecânicos são responsáveis por realizar atividades voltadas a sistemas mecânicos, englobando as aplicações contidas nas macroáreas da profissão: materiais, processos de fabricação, projetos mecânicos e gestão.",
        salario: "R$ 8.230 em média",
        cargaHoraria: "42 horas semanais",
        observacao: "",
        inteligencias: "Lógico-matemática 40%; Espacial 40%; Corporal cinestésica 20%",
    },
    {
        id: 43,
        titulo: "Estatística",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-Matemática 80%; Intrapessoal 20%",
        estrelas: 3,
        breveDescricao:
            "A Estatística é o campo da matemática que relaciona fatos e números em que há um conjunto de métodos que nos possibilita coletar dados e analisá-los, assim sendo possível realizar alguma interpretação deles.",
        salario: "Pode vir a ganhar R$ 7.210",
        cargaHoraria: "41 horas semanais",
        observacao: "",
        inteligencias: "Lógico-Matemática 80%; Intrapessoal 20%",
    },
    {
        id: 44,
        titulo: "Geofísica",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 50%; Espacial 30%; Existencial 20%",
        estrelas: 5,
        breveDescricao:
            "O geofísico é o profissional que analisa as propriedades físicas dos principais processos do planeta terra. O trabalho do especialista é compreender os fenômenos sísmicos, elétricos, gravitacionais e magnéticos que incidem sobre o planeta.",
        salario: "R$ 9.892,00 em média",
        cargaHoraria: "42 horas semanais",
        observacao: "",
        inteligencias: "Naturalista 50%; Espacial 30%; Existencial 20%",
    },
    {
        id: 45,
        titulo: "Logística",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática 80%; Espacial 20%",
        estrelas: 3,
        breveDescricao:
            "O profissional de logística é responsável por lidar com as atividades no setor, desde produção, passando pelo armazenamento e distribuição dos produtos, em centros de distribuição, transportadoras, portos, aeroportos, terminais de carga, lojas de móveis, comércio e indústria.",
        salario: "R$ 2.153 em média",
        cargaHoraria: "44 horas semanais",
        observacao: "",
        inteligencias: "Lógico-matemática 80%; Espacial 20%",
    },
    {
        id: 46,
        titulo: "Tecnologia da Informação",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática",
        estrelas: 5,
        breveDescricao:
            "O profissional de TI é o responsável por gerenciar as informações em uma organização, criando e distribuindo-as em redes de computadores, além de lidar com processamento de dados, engenharia de software, informática, hardwares e softwares.",
        salario: "Em média R$ 8.544",
        cargaHoraria: "40 horas semanais",
        observacao: "É uma das carreiras que mais oferecem oportunidades de emprego atualmente.",
        inteligencias: "Lógico-matemática",
    },
    {
        id: 47,
        titulo: "Filosofia",
        imgSrc: "/img/existencial.svg",
        tipo: "Existencial 60%; Intrapessoal 20%; Interpessoal 15%; Linguística 5%",
        estrelas: 4,
        breveDescricao:
            "Filósofo é a pessoa responsável por estudar a natureza de todas as coisas existentes e as relações que possam existir entre estas coisas. Noções de valores, sentidos, fatos, além da conduta e destino do homem também são temas estudados por este profissional.",
        salario: "R$ 2.071,17 em média",
        cargaHoraria: "37 horas semanais",
        observacao: "A média salarial e carga horária tende a variar a depender do segmento.",
        inteligencias: "Existencial 60%; Intrapessoal 20%; Interpessoal 15%; Linguística 5%",
    },
    {
        id: 48,
        titulo: "História",
        imgSrc: "/img/existencial.svg",
        tipo: "Existencial 40%; Intrapessoal 20%; Interpessoal 20%; Linguística 20%",
        estrelas: 3,
        breveDescricao:
            "História é a ciência que estuda o ser humano e sua ação no tempo e no espaço concomitantemente à análise de processos e eventos ocorridos no passado.",
        salario: "Em média R$ 2.659,50",
        cargaHoraria: "44 horas semanais",
        observacao: "A média salarial e carga horária tende a variar a depender do segmento.",
        inteligencias: "Existencial 40%; Intrapessoal 20%; Interpessoal 20%; Linguística 20%",
    },
    {
        id: 49,
        titulo: "Sociologia",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 40%; Existencial 40%; Intrapessoal 10%; Linguística 10%",
        estrelas: 3,
        breveDescricao:
            "A Sociologia é uma das ciências humanas que estuda a sociedade, ou seja, estuda o comportamento humano em função do meio e os processos que interligam os indivíduos em associações, grupos e instituições.",
        salario: "Em média R$ 2.334,00",
        cargaHoraria: "A média salarial e carga horária tende a variar a depender do segmento.",
        observacao: "",
        inteligencias: "Interpessoal 40%; Existencial 40%; Intrapessoal 10%; Linguística 10%",
    },
    {
        id: 50,
        titulo: "Teologia",
        imgSrc: "/img/existencial.svg",
        tipo: "Existencial 50%; Intrapessoal 35%; Linguística 15%",
        estrelas: 4,
        breveDescricao:
            "Teologia é o estudo crítico da natureza dos deuses, seres divinos, ou de Deus, seus atributos e sua relação com os homens, com o objetivo de examinar a natureza de Deus, a natureza humana, a moralidade, a espiritualidade e outras questões relacionadas à fé.",
        salario: "R$ 2.155 em média",
        cargaHoraria: "27h semanais",
        observacao: "A média salarial e carga horária tende a variar a depender do segmento.",
        inteligencias: "Existencial 50%; Intrapessoal 35%; Linguística 15%",
    },
    {
        id: 51,
        titulo: "Ciência Política",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 40%; Existencial 35%; Linguística 25%",
        estrelas: 4,
        breveDescricao:
            "Ciência Política estuda as relações de poder e seus impactos na sociedade. Durante os últimos anos, o tema vem em uma crescente, demandando a presença de profissionais capazes de analisar detalhadamente o cenário e auxiliar na veiculação de respaldos técnicos do setor, funções relacionadas ao cientista político.",
        salario: "R$ 5.865 em média",
        cargaHoraria: "44 horas semanais",
        observacao: "A média salarial e carga horária tende a variar a depender do segmento.",
        inteligencias: "Interpessoal 40%; Existencial 35%; Linguística 25%",
    },
    {
        id: 52,
        titulo: "Administração",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática 80%; Interpessoal 20%",
        estrelas: 4,
        breveDescricao:
            "Administração é a tomada de decisão sobre recursos disponíveis, trabalhando com e através de pessoas para atingir objetivos, é o gerenciamento de uma organização, levando em conta as informações fornecidas por outros profissionais e também pensando previamente as consequências de suas decisões.",
        salario: "R$ 3.095 em média",
        cargaHoraria: "44 horas semanais ou 48 horas (com as horas extras)",
        observacao: "",
        inteligencias: "Lógico-matemática 80%; Interpessoal 20%",
    },
    {
        id: 53,
        titulo: "Biblioteconomia",
        imgSrc: "/img/linguistica.svg",
        tipo: "Linguística 80%; Intrapessoal 10%; Espacial 10%",
        estrelas: 3,
        breveDescricao:
            "Biblioteconomia é a ciência que estuda a produção, a organização, a conservação, a comunicação e a utilização de informação, documentos e materiais bibliográficos. Estuda também a gestão de bibliotecas e outros serviços de informação.",
        salario: "R$ 4.120 em média",
        cargaHoraria: "40 horas semanais",
        observacao: "",
        inteligencias: "Linguística 80%; Intrapessoal 10%; Espacial 10%",
    },
    {
        id: 54,
        titulo: "Contabilidade",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-Matemática",
        estrelas: 3,
        breveDescricao:
            "Contabilidade é responsável pelo controle do movimento financeiro de empresas no que se refere à apuração de impostos e de taxas referentes à prestação de serviços e produtos.",
        salario: "R$ 4.900 em média",
        cargaHoraria: "44 horas semanais",
        observacao: "",
        inteligencias: "Lógico-Matemática",
    },
    {
        id: 55,
        titulo: "Eventos",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 80%; Espacial 20%",
        estrelas: 3,
        breveDescricao:
            "A faculdade de Eventos prepara o profissional para planejar, desenvolver e organizar eventos dos mais variados tipos. Isso inclui desde projetos socioculturais, eventos corporativos, de lazer, de artes, científicos, de turismo ou mesmo esportivos.",
        salario: "R$ 2.385,00 em média",
        cargaHoraria: "43 horas semanais",
        observacao: "O salário tende a variar dependendo da clientela.",
        inteligencias: "Interpessoal 80%; Espacial 20%",
    },
    {
        id: 56,
        titulo: "Jornalismo",
        imgSrc: "/img/linguistica.svg",
        tipo: "Linguística 45%; Interpessoal 45%; Existencial 10%",
        estrelas: 4,
        breveDescricao:
            "Jornalistas investigam, compreendem, narram e informam sobre os acontecimentos, fatos ou situações que dizem respeito à sociedade. Além disso, são preparados para redigir textos, organizar pautas, editar matérias, planejar e executar coberturas jornalísticas e realizar entrevistas.",
        salario: "R$ 3.361,54 em média",
        cargaHoraria: "5 horas diárias",
        observacao: "",
        inteligencias: "Linguística 45%; Interpessoal 45%; Existencial 10%",
    },
    {
        id: 57,
        titulo: "Publicidade e Propaganda",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 50%; Espacial 35%; Musical 15%",
        estrelas: 4,
        breveDescricao:
            "Profissionais de Publicidade e Propaganda podem criar campanhas publicitárias, desenhar logotipos, criar embalagens de produtos, desenvolver e manter a imagem de uma marca e elaborar estratégias de vendas, entre outros.",
        salario: "R$ 3.000",
        cargaHoraria: "42 horas semanais",
        observacao: "O salário tende a variar dependendo da clientela.",
        inteligencias: "Interpessoal 50%; Espacial 35%; Musical 15%",
    },
    {
        id: 58,
        titulo: "Recursos Humanos",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 70%; Lógico-matemática 30%",
        estrelas: 4,
        breveDescricao:
            "Recursos Humanos é um dos principais setores de uma empresa e realiza o gerenciamento assertivo e humanizado dos colaboradores, tendo um papel altamente analítico e estratégico.",
        salario: "R$ 4.090 em média",
        cargaHoraria: "8 horas diárias",
        observacao: "",
        inteligencias: "Interpessoal 70%; Lógico-matemática 30%",
    },
    {
        id: 59,
        titulo: "Segurança do Trabalho",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 50%; Espacial 30%; Corporal-cinestésica",
        estrelas: 3,
        breveDescricao:
            "Segurança do Trabalho é uma ciência que tem o objetivo de promover a proteção do trabalhador em seu local de trabalho, visando a redução de acidentes de trabalho e doenças ocupacionais.",
        salario: "R$ 2.977 em média",
        cargaHoraria: "44 horas semanais",
        observacao: "",
        inteligencias: "Interpessoal 50%; Espacial 30%; Corporal-cinestésica",
    },
    {
        id: 60,
        titulo: "Artes Cênicas",
        imgSrc: "/img/intrapessoal.svg",
        tipo: "Intrapessoal 30%; Corporal-cinestésica 30%; Espacial 20%; Interpessoal 20%",
        estrelas: 3,
        breveDescricao:
            "Artes Cênicas ou performativas incluem música, dança e teatro, realizadas para um público. Diferente das artes visuais, que usam materiais para criar objetos físicos ou estáticos.",
        salario: "R$ 2300,00 em média",
        cargaHoraria: "38 horas semanais",
        observacao: "O salário e carga horária tendem a variar dependendo da clientela.",
        inteligencias: "Intrapessoal 30%; Corporal-cinestésica 30%; Espacial 20%; Interpessoal 20%",
    },
    {
        id: 61,
        titulo: "Artes Plásticas",
        imgSrc: "/img/intrapessoal.svg",
        tipo: "Intrapessoal 30%; Espacial 30%; Existencial 25%; Musical 15%",
        estrelas: 2,
        breveDescricao:
            "Artes Plásticas são formações expressivas realizadas com técnicas de produção que manipulam materiais para construir formas e imagens esteticamente e poeticamente concebidas.",
        salario: "R$ 1.759 em média",
        cargaHoraria: "20 horas semanais",
        observacao: "A carga horária tende a variar dependendo da clientela.",
        inteligencias: "Intrapessoal 30%; Espacial 30%; Existencial 25%; Musical 15%",
    },
    {
        id: 62,
        titulo: "Dança",
        imgSrc: "/img/corporalCin.webp",
        tipo: "Corporal-cinestésica 50%; Interpessoal 20%; Intrapessoal 20%; Musical 10%",
        estrelas: 3,
        breveDescricao:
            "Profissionais de Dança conhecem técnicas de movimentação corporal para criar e executar coreografias em espetáculos de dança, teatro, shows, etc.",
        salario: "R$ 1.570 em média",
        cargaHoraria: "Varia muito em relação à clientela.",
        observacao: "O salário e carga horária variam muito dependendo da clientela.",
        inteligencias: "Corporal-cinestésica 50%; Interpessoal 20%; Intrapessoal 20%; Musical 10%",
    },
    {
        id: 63,
        titulo: "Design de Games",
        imgSrc: "/img/intrapessoal.svg",
        tipo: "Intrapessoal 35%; Lógico-matemática 30%; Espacial 25%; Musical 10%",
        estrelas: 4,
        breveDescricao:
            "O designer de jogos desenvolve o conceito criativo de videogames, incluindo universo, estilo de jogo, enredo, personagens, jogabilidade, estética, objetivos, fases, interface e experiência do usuário.",
        salario: "R$ 4.476",
        cargaHoraria: "44 horas semanais",
        observacao: "",
        inteligencias: "Intrapessoal 35%; Lógico-matemática 30%; Espacial 25%; Musical 10%",
    },
    {
        id: 64,
        titulo: "Design de Moda",
        imgSrc: "/img/interpessoal.svg",
        tipo: "Interpessoal 35%; Intrapessoal 30%; Musical 20%; Espacial 15%",
        estrelas: 3,
        breveDescricao:
            "Design de moda é a arte da aplicação do design e estética em roupas e acessórios, influenciado por latitudes culturais e sociais.",
        salario: "R$ 2.300,00 em média",
        cargaHoraria: "43 horas semanais",
        observacao: "",
        inteligencias: "Interpessoal 35%; Intrapessoal 30%; Musical 20%; Espacial 15%",
    },
    {
        id: 65,
        titulo: "Design de Interiores",
        imgSrc: "/img/espacial.svg",
        tipo: "Espacial 80%; Intrapessoal 20%",
        estrelas: 4,
        breveDescricao:
            "O designer de interiores planeja e projeta espaços internos, considerando estética, conforto, saúde, segurança e funcionalidade.",
        salario: "R$ 2.968,00 em média",
        cargaHoraria: "42 horas semanais",
        observacao: "",
        inteligencias: "Espacial 80%; Intrapessoal 20%",
    },
    {
        id: 66,
        titulo: "Fotografia",
        imgSrc: "/img/intrapessoal.svg",
        tipo: "Intrapessoal 50%; Espacial 40%; Musical 10%",
        estrelas: 3,
        breveDescricao:
            "Fotografia é a técnica de criar imagens por meio da exposição luminosa, combinando luz, composição, ângulos e cores para criar imagens únicas.",
        salario: "R$ 1.834 em média",
        cargaHoraria: "44 horas semanais",
        observacao: "O salário e carga horária variam muito dependendo da clientela.",
        inteligencias: "Intrapessoal 50%; Espacial 40%; Musical 10%",
    },
    {
        id: 67,
        titulo: "Zootecnia",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 80%; Intrapessoal 20%",
        estrelas: 3,
        breveDescricao:
            "Zootecnia é a ciência que desenvolve e aprimora as potencialidades de animais, visando melhorar sua produção por meio de nutrição, seleção genética, sanidade e bem-estar.",
        salario: "R$ 3.152,00 em média",
        cargaHoraria: "6 horas diárias",
        observacao: "",
        inteligencias: "Naturalista 80%; Intrapessoal 20%",
    },
    {
        id: 68,
        titulo: "Analista de Dados",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática",
        estrelas: 4,
        breveDescricao:
            "Analista de Dados administra servidores, acompanha desempenho, programa rotinas e garante a segurança, além de cuidar de KPIs, identificar e solucionar problemas.",
        salario: "R$ 6.000 em média",
        cargaHoraria: "40 horas semanais",
        observacao: "Salário tende a crescer com experiência.",
        inteligencias: "Lógico-matemática",
    },
    {
        id: 69,
        titulo: "Secretariado",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática 70%; Interpessoal 30%",
        estrelas: 3,
        breveDescricao:
            "Secretariado envolve organizar o ambiente de trabalho, atender clientes, prestar informações, arquivar documentos e participar de reuniões.",
        salario: "R$ 3.338 em média",
        cargaHoraria: "44 horas semanais",
        observacao: "",
        inteligencias: "Lógico-matemática 70%; Interpessoal 30%",
    },
    {
        id: 70,
        titulo: "Biólogo",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista",
        estrelas: 3,
        breveDescricao:
            "Biólogo estuda a vida e organismos vivos, analisando estrutura, crescimento, funcionamento, reprodução, origem, evolução, distribuição e relações com o ambiente.",
        salario: "R$ 2.996,82 em média",
        cargaHoraria: "30 horas semanais",
        observacao: "",
        inteligencias: "Naturalista",
    },
    {
        id: 71,
        titulo: "Físico",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática 50%; Naturalista 35%; Existencial 15%",
        estrelas: 4,
        breveDescricao:
            "O físico estuda a natureza e fenômenos do nível subatômico ao cosmológico, desenvolvendo teorias, modelos e experimentos.",
        salario: "R$ 3.170,00 em média",
        cargaHoraria: "41 horas semanais",
        observacao: "O salário pode ser maior dependendo do local de trabalho.",
        inteligencias: "Lógico-matemática 50%; Naturalista 35%; Existencial 15%",
    },
    {
        id: 72,
        titulo: "Químico",
        imgSrc: "/img/naturalista.svg",
        tipo: "Naturalista 50%; Lógico-matemática 50%",
        estrelas: 3,
        breveDescricao:
            "O químico analisa substâncias, compostos, características físico-químicas e reações a variações de pressão e temperatura.",
        salario: "R$ 4.360,00 em média",
        cargaHoraria: "42 horas",
        observacao: "",
        inteligencias: "Naturalista 50%; Lógico-matemática 50%",
    },
    {
        id: 73,
        titulo: "Matemática",
        imgSrc: "/img/logico.svg",
        tipo: "Lógico-matemática",
        estrelas: 4,
        breveDescricao:
            "O matemático estuda a ciência matemática, trabalhando com problemas, sistemas, fórmulas e teses matemáticas, visando descobrir novas técnicas ou aprimorar as existentes.",
        salario: "R$ 3.846,08 em média",
        cargaHoraria: "40 horas semanais",
        observacao: "O salário pode ser maior dependendo do local de trabalho.",
        inteligencias: "Lógico-matemática",
    },
    {
        id: 74,
        titulo: "Escritor",
        imgSrc: "/img/linguistica.svg",
        tipo: "Linguística 50%; Intrapessoal 50%",
        estrelas: 3,
        breveDescricao:
            "O escritor redige textos e obras literárias, elaborando livros, artigos, críticas, resenhas, crônicas e outros gêneros textuais.",
        salario: "R$ 2.145,00 em média",
        cargaHoraria: "Não definido",
        observacao: "A carga horária e a média salarial variam muito dependendo da clientela.",
        inteligencias: "Linguística 50%; Intrapessoal 50%",
    },
    {
        id: 75,
        titulo: "Dublagem",
        imgSrc: "/img/corporalCin.webp",
        tipo: "Corporal-Cinestésica 40%; Musical 40%; Interpessoal 20%",
        estrelas: 3,
        breveDescricao:
            "Dublagem é a substituição da voz original em produções audiovisuais pela voz e interpretação de um ator, frequentemente em outro idioma.",
        salario: "R$ 2.458,18",
        cargaHoraria: "6 horas diárias",
        observacao: "",
        inteligencias: "Corporal-Cinestésica 40%; Musical 40%; Interpessoal 20%",
    },
];
