import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Background } from "../components/background";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flyvoo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Background />
        {children}
      </body>
    </html>
  );
}
